name: Playwright Tests
on:
  pull_request:
    branches: ["main"]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build & Install
      run: cd RestfulBookerTests && dotnet build && dotnet tool install --global PowerShell
    - name: Run your tests
      run: cd RestfulBookerTests && dotnet test --logger "html;logfilename=testResults.html"